# UNVERIFIED DECOMPILER OUTPUT: may contain incorrect behavior.
# Source Generated with Decompyle++
# File: packaging.marshal (Python 3.9)

'''Cross-platform-safe product artifact assembly helpers.'''
from macos_control import MACOS_CONTROL_EXECUTABLE_NAME, MACOS_CONTROL_FRONTEND_RELATIVE_PATH, MACOS_FRONTEND_RUNTIME_MODE, MACOS_FRONTEND_STARTUP_PRESENTATION, MACOS_MVP_BUILD_CHANNEL, MACOS_MVP_CAPABILITY_WAVES, MACOS_PRODUCTION_BUILD_CHANNEL, MACOS_HELPER_EXECUTABLE_NAME, MacOSControlPackagingError, assemble_unsigned_macos_control_bundle, inspect_macos_control_bundle, inspect_macos_frontend_directory, resolve_macos_control_frontend_directory
from macos_helper import MACOS_HELPER_APP_NAME, MACOS_HELPER_ICON_NAME, MACOS_HELPER_MINIMUM_SYSTEM_VERSION, MACOS_HELPER_SWIFT_FRAMEWORKS, MACOS_HELPER_SWIFT_SOURCE_NAMES, MacOSHelperBuildError, MacOSHelperBuildRequest, build_signed_macos_helper
from macos_release import MACOS_AGENT_PLUGIN_ARCHITECTURE, MACOS_AGENT_PLUGIN_BUILD_CHANNEL, MACOS_AGENT_PLUGIN_CAPABILITY_WAVE, MACOS_AGENT_PLUGIN_DRIVER_API_VERSION, MACOS_AGENT_PLUGIN_HANDOFF_KIND, MACOS_AGENT_PLUGIN_MINIMUM_SYSTEM_VERSION, MACOS_AGENT_PLUGIN_RELEASE_CHANNEL, MACOS_AGENT_PLUGIN_RUNTIME_CONTRACT_VERSION, MACOS_CONTROL_APP_NAME, MACOS_FRONTEND_NODE_VERSION, MACOS_FRONTEND_NPM_VERSION, MACOS_FRONTEND_TEST_SCRIPTS, MACOS_RELEASE_REPORT_NAME, MACOS_RELEASE_STATE_NAME, MACOS_RELEASE_TEST_PATTERNS, MacOSAgentPluginReleaseError, MacOSAgentPluginReleaseRequest, build_macos_agent_plugin_release
__all__ = [
    'MACOS_CONTROL_EXECUTABLE_NAME',
    'MACOS_CONTROL_FRONTEND_RELATIVE_PATH',
    'MACOS_FRONTEND_RUNTIME_MODE',
    'MACOS_FRONTEND_STARTUP_PRESENTATION',
    'MACOS_MVP_BUILD_CHANNEL',
    'MACOS_MVP_CAPABILITY_WAVES',
    'MACOS_PRODUCTION_BUILD_CHANNEL',
    'MACOS_HELPER_EXECUTABLE_NAME',
    'MACOS_HELPER_APP_NAME',
    'MACOS_HELPER_ICON_NAME',
    'MACOS_HELPER_MINIMUM_SYSTEM_VERSION',
    'MACOS_HELPER_SWIFT_FRAMEWORKS',
    'MACOS_HELPER_SWIFT_SOURCE_NAMES',
    'MACOS_AGENT_PLUGIN_ARCHITECTURE',
    'MACOS_AGENT_PLUGIN_BUILD_CHANNEL',
    'MACOS_AGENT_PLUGIN_CAPABILITY_WAVE',
    'MACOS_AGENT_PLUGIN_DRIVER_API_VERSION',
    'MACOS_AGENT_PLUGIN_HANDOFF_KIND',
    'MACOS_AGENT_PLUGIN_MINIMUM_SYSTEM_VERSION',
    'MACOS_AGENT_PLUGIN_RELEASE_CHANNEL',
    'MACOS_AGENT_PLUGIN_RUNTIME_CONTRACT_VERSION',
    'MACOS_CONTROL_APP_NAME',
    'MACOS_FRONTEND_NODE_VERSION',
    'MACOS_FRONTEND_NPM_VERSION',
    'MACOS_FRONTEND_TEST_SCRIPTS',
    'MACOS_RELEASE_REPORT_NAME',
    'MACOS_RELEASE_STATE_NAME',
    'MACOS_RELEASE_TEST_PATTERNS',
    'MacOSAgentPluginReleaseError',
    'MacOSAgentPluginReleaseRequest',
    'MacOSControlPackagingError',
    'MacOSHelperBuildError',
    'MacOSHelperBuildRequest',
    'assemble_unsigned_macos_control_bundle',
    'build_signed_macos_helper',
    'build_macos_agent_plugin_release',
    'inspect_macos_control_bundle',
    'inspect_macos_frontend_directory',
    'resolve_macos_control_frontend_directory']
