# UNVERIFIED DECOMPILER OUTPUT: may contain incorrect behavior.
# Source Generated with Decompyle++
# File: resolution.marshal (Python 3.9)

'''Pure resolution of build discovery and account execution capabilities.'''
from typing import Dict, Iterable, Mapping, Optional, Tuple
from WeRobotCore.domain import CapabilityName, CapabilityState, CapabilityStatus
from WeRobotCore.ports import PermissionState, PermissionStatus
from contract import RuntimeCapabilityProvider
BUILD_CAPABILITY_NOT_DECLARED = 'BUILD_CAPABILITY_NOT_DECLARED'
BUILD_CAPABILITY_UNAVAILABLE = 'BUILD_CAPABILITY_UNAVAILABLE'
BUILD_PERMISSION_REQUIREMENTS_NOT_DECLARED = 'BUILD_PERMISSION_REQUIREMENTS_NOT_DECLARED'
INSTANCE_CAPABILITY_NOT_DECLARED = 'INSTANCE_CAPABILITY_NOT_DECLARED'
INSTANCE_CAPABILITY_UNAVAILABLE = 'INSTANCE_CAPABILITY_UNAVAILABLE'
INSTANCE_CLIENT_VERSION_UNSUPPORTED = 'INSTANCE_CLIENT_VERSION_UNSUPPORTED'
INSTANCE_PERMISSION_REQUIRED = 'INSTANCE_PERMISSION_REQUIRED'
INSTANCE_PERMISSION_REQUIREMENTS_NOT_DECLARED = 'INSTANCE_PERMISSION_REQUIREMENTS_NOT_DECLARED'
PERMISSION_STATE_NOT_DECLARED = 'PERMISSION_STATE_NOT_DECLARED'
PERMISSION_DENIED = 'PERMISSION_DENIED'
PERMISSION_NOT_DETERMINED = 'PERMISSION_NOT_DETERMINED'
PERMISSION_UNAVAILABLE = 'PERMISSION_UNAVAILABLE'
CAPABILITY_EXPERIMENTAL = 'CAPABILITY_EXPERIMENTAL'
_KNOWN_CAPABILITY_NAMES = frozenset((lambda .0: for item in .0:
item.value)(CapabilityName))

def _merge_permissions(*groups):
